pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG = "${WORKSPACE}/sonar/ansible/ansible.cfg"
    ANSIBLE_PYTHON_INTERPRETER = "/usr/bin/python3"
  }

  stages {
    stage('Terraform Init & Apply') {
      steps {
        dir('sonar/terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Ansible Inventory Check') {
      steps {
        dir('sonar/ansible') {
          // Validate inventory and host discovery
          sh 'ansible-inventory -i aws_ec2.yaml --graph'
          sh 'ansible -i aws_ec2.yaml tag_SonarQube_Server -m ping -e ansible_python_interpreter=${ANSIBLE_PYTHON_INTERPRETER}'
        }
      }
    }

    stage('Ansible Provisioning') {
      steps {
        dir('sonar/ansible') {
          script {
            try {
              sh 'ansible-playbook -i aws_ec2.yaml playbook.yml -e ansible_python_interpreter=${ANSIBLE_PYTHON_INTERPRETER}'
            } catch (Exception e) {
              echo "Provisioning failed: ${e.getMessage()}"
              currentBuild.result = 'FAILURE'
            }
          }
        }
      }
    }
  }
}
