- name: Configure SonarQube
  hosts: tag_SonarQube_Server
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites (Java 17, wget, unzip)
      apt:
        name:
          - openjdk-17-jdk
          - wget
          - unzip
        state: present

    - name: Create sonar group
      group:
        name: sonar
        state: present

    - name: Create sonar user
      user:
        name: sonar
        group: sonar
        system: yes
        shell: /bin/bash
        create_home: no

    - name: Download SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.4.87374.zip
        dest: /tmp/sonarqube.zip

    - name: Extract SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes
        creates: /opt/sonarqube-9.9.4.87374

    - name: Create symlink
      file:
        src: /opt/sonarqube-9.9.4.87374
        dest: /opt/sonarqube
        state: link
        force: yes

    - name: Set ownership of SonarQube directory
      file:
        path: /opt/sonarqube-9.9.4.87374
        state: directory
        recurse: yes
        owner: sonar
        group: sonar

    - name: Set SONARQUBE_HOME environment variable
      lineinfile:
        dest: /etc/environment
        line: 'SONARQUBE_HOME=/opt/sonarqube'
        state: present

    - name: Add SonarQube systemd service
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking
          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
          User=sonar
          Group=sonar
          Restart=always
          LimitNOFILE=65536
          LimitNPROC=4096
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start SonarQube
      systemd:
        name: sonarqube
        enabled: yes
        state: started
